"""Slot-based query analysis — the first LLM decision point.

Turns a natural-language research question into the three artifacts the rest of the
pipeline is built on:

``structured_keywords``   ``[("alignment", "factual"), ("metric",)]`` — head term plus
                          modifier.  Reversed and joined, these form the text the
                          reranker scores every paper against.
``search_queries``        the keyword strings handed to Semantic Scholar.
``discriminative_terms``  ``{term: rarity 1-10}`` — drives ``keyword_match_score``.

All three come from one three-turn conversation: turn 2 and turn 3 are continuations of
turn 1, so the model can refer back to the keywords it just produced.  Reproducing that
history is important — asking for search queries cold gives materially different output.

This replaces the earlier port, which had brought across a *different*, older analyzer
that produced only ``core_keywords`` + weighted criteria and none of the three fields
above.  The batch evaluation configs were generated by this one
(``run_my_method/01_generate_query_configs.py``).
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional, Sequence, Tuple

from metasci_citeflow.llm.client import load_prompts
from metasci_citeflow.llm.parsers import (
    parse_discriminative_terms,
    parse_search_queries,
    parse_slot_keywords,
)

logger = logging.getLogger(__name__)

PROMPTS_FILE = "slot_based_prompts.yaml"


def rerank_query_text(structured_keywords: Sequence[Sequence[str]]) -> str:
    """Build the reranker's query string from structured keywords.

    Each tuple is reversed then space-joined, so ``("alignment", "factual")`` becomes
    ``"factual alignment"`` — modifier first, which reads as natural English and is what
    the cross-encoder was scored against in the original runs.
    """
    parts = []
    for group in structured_keywords or []:
        words = [str(word).strip() for word in reversed(list(group)) if str(word).strip()]
        if words:
            parts.append(" ".join(words))
    return " ".join(parts)


class SlotBasedQueryAnalyzer:
    """Three-turn query analysis against an OpenAI-compatible model."""

    def __init__(self, llm: Any, model: Optional[str] = None, temperature: float = 0.5) -> None:
        self.llm = llm
        self.model = model
        self.temperature = temperature
        self.prompts = load_prompts(PROMPTS_FILE)

    async def _turn(
        self,
        prompt_key: str,
        *,
        history: Optional[List[Dict[str, str]]] = None,
        **fields: Any,
    ) -> str:
        config = self.prompts[prompt_key]
        return await self.llm.complete(
            system=config["system"],
            user=config["user"].format(**fields),
            model=self.model,
            temperature=self.temperature,
            history=history,
            prompt_key=prompt_key,
        )

    async def analyze(self, query: str) -> Dict[str, Any]:
        """Turn 1 — extract structured keywords, returning the conversation history."""
        config = self.prompts["slot_keywords"]
        system = config["system"]
        user = config["user"].format(query=query)
        raw = await self.llm.complete(
            system=system,
            user=user,
            model=self.model,
            temperature=self.temperature,
            prompt_key="slot_keywords",
        )
        result = parse_slot_keywords(raw)
        result["_history"] = [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
            {"role": "assistant", "content": raw},
        ]
        return result

    async def format_keywords_for_search(
        self,
        keywords: Sequence[Sequence[str]],
        history: Optional[List[Dict[str, str]]] = None,
    ) -> Dict[str, Any]:
        """Turn 2 — turn structured keywords into Semantic Scholar query strings."""
        if not keywords:
            return {"reasoning": "", "queries": []}
        raw = await self._turn(
            "format_search_queries", history=history, keywords=str(_as_tuples(keywords))
        )
        return parse_search_queries(raw)

    async def extract_discriminative_terms(
        self,
        keywords: Sequence[Sequence[str]],
        history: Optional[List[Dict[str, str]]] = None,
    ) -> Dict[str, Any]:
        """Turn 3 — score terms by how well they discriminate within the domain."""
        if not keywords:
            return {"reasoning": "", "terms": {}}
        raw = await self._turn(
            "extract_discriminative_terms", history=history, keywords=str(_as_tuples(keywords))
        )
        return parse_discriminative_terms(raw)

    async def analyze_all(self, query: str) -> Dict[str, Any]:
        """Run all three turns and return the combined analysis."""
        first = await self.analyze(query)
        keywords = first.get("core_keywords") or []
        history = first.get("_history") or []

        search = await self.format_keywords_for_search(keywords, history)
        terms = await self.extract_discriminative_terms(keywords, history)

        analysis: Dict[str, Any] = {
            "query": query,
            "structured_keywords": [list(group) for group in keywords],
            "search_queries": search.get("queries", []),
            "discriminative_terms": terms.get("terms", {}),
            "rerank_query": rerank_query_text(keywords),
            "reasoning": {
                "structured_keywords": first.get("reasoning", ""),
                "search_queries": search.get("reasoning", ""),
                "discriminative_terms": terms.get("reasoning", ""),
            },
        }
        if first.get("_parse_error"):
            analysis["parse_error"] = first["_parse_error"]
        return analysis


def _as_tuples(keywords: Sequence[Sequence[str]]) -> List[Tuple[str, ...]]:
    """Render keywords as Python tuples, matching how the prompts were written."""
    return [tuple(group) for group in keywords]


def analysis_from_config(config: Dict[str, Any]) -> Dict[str, Any]:
    """Build an analysis payload from an original AcaDeepR config file.

    Pinning the analysis removes the run-to-run variance of the first LLM turn, which is
    what makes an A/B comparison against the published numbers meaningful.
    """
    keywords = [tuple(group) for group in (config.get("structured_keywords") or [])]
    return {
        "query": config.get("query", ""),
        "structured_keywords": [list(group) for group in keywords],
        "search_queries": list(config.get("search_queries") or []),
        "discriminative_terms": dict(config.get("discriminative_terms") or {}),
        "rerank_query": rerank_query_text(keywords),
        "reasoning": {"source": "pinned from config"},
    }
